In [1]:
import numpy as np

In [2]:
Y = np.array([
    [5, np.nan, 7],
    [np.nan, 2, np.nan],
    [4, np.nan, np.nan],
    [np.nan, 3, 6]
])
lbda = 1 # lambda
u, v = np.array([[6], [0], [3], [6]]), np.array([[4],[2],[1]])  # weird but furces u and v to be column vectors

print(f' Y:\n {Y},\n\n u:\n {u},\n\n v:\n {v}')

 Y:
 [[ 5. nan  7.]
 [nan  2. nan]
 [ 4. nan nan]
 [nan  3.  6.]],

 u:
 [[6]
 [0]
 [3]
 [6]],

 v:
 [[4]
 [2]
 [1]]


In [3]:
u.dot(v.transpose()) # question 1a

array([[24, 12,  6],
       [ 0,  0,  0],
       [12,  6,  3],
       [24, 12,  6]])

In [4]:
def compute_u(Y, v, _lambda):
    # 1 if (a, i) given and 0 otherwise:
    given_values_positions = np.where(np.isnan(Y), 0, 1) 
    # # sum from i=1 to m of (v_i)^2, for each a considering only (a, i) in D
    v_sq_sum_given = given_values_positions.dot(v*v)  
    # # y*v/(lambda + v^2) for (a, i) in D, an n-dim vector
    fitted_u = np.nan_to_num(Y).dot(v) / ( _lambda + v_sq_sum_given ) 
    return fitted_u

U1 = compute_u(Y=Y, v=v, _lambda=lbda)
print(U1)

[[1.5       ]
 [0.8       ]
 [0.94117647]
 [2.        ]]


In [5]:
# I did not test this one, but used similar logic

def compute_v(Y, u, _lambda):
    given_values_positions = np.where(np.isnan(Y), 0, 1).transpose() # 1 if (a, i) given and 0 otherwise
    Y = np.nan_to_num(Y) # fill nan with 0's
    u_sq_sum_given = given_values_positions.dot(u*u) # sum from i=1 to m of (v_i)^2, for each a considering only (a, i) in D 
    fitted_v = Y.transpose().dot(u) / ( _lambda + u_sq_sum_given ) # y*u/(lambda + v^2) for (a, i) in D, an m-dim vector
    return fitted_v
V1 = compute_v(Y=Y, u=u, _lambda=lbda)
print(V1)

[[0.91304348]
 [0.48648649]
 [1.06849315]]
